path:
    train_path: ../../dataset/train/train.csv
    test_path: ../../dataset/test/test_data.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: klue/bert-base
    saved_name: base

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 1
    learning_rate: 3e-5
    logging_step: 5
    nums_folds: 5
    
wandb:
    wandb_username: rion_
    wandb_project: sts
    wandb_entity: sts_et
