path:
    train_path: ../../dataset/train/train.csv
    test_path: ../../dataset/test/test_data.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: snunlp/KR-ELECTRA-discriminator
    saved_name: base

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 1
    learning_rate: 1e-5
    logging_step: 5
    nums_folds: 5
    loss_name: CrossEntropy # CrossEntropy, focal, label_smoothing, f1
    optimizer_name: AdamW
    lr_decay_step: 20
    scheduler_name: StepLR # StepLR, ReduceLROnPlateau, CosineAnnealingLR
wandb:
    wandb_username: daniel0801
    wandb_project: sts
    wandb_entity: sts_et
