path:
    train_path: ../../../dataset/train/multi_label_aug_com.csv
    test_path: ../../../dataset/test/test_data.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
    
model:
    model_name: monologg/kobigbird-bert-base
    saved_name: kobigbird

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 10
    learning_rate: 2.1216154368926846e-05
    logging_step: 5
    nums_folds: 5
    loss_name: label_smoothing # CrossEntropy, focal, label_smoothing, f1
    optimizer_name: AdamW
    lr_sch_use: False
    lr_decay_step: 20
    scheduler_name: constant_warmup # StepLR, ReduceLROnPlateau, CosineAnnealingLR, constant_warmup
    lr_weight_decay: True
    
wandb:
    wandb_username: rion_
    wandb_project: huggingface
    wandb_entity: re_et
