path:
    train_path: ../../dataset/train/train.csv
    test_path: ../../dataset/test/test_data.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등

model:
    model_name: klue/roberta-large
    saved_name: roberta-large/orig

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 3
    learning_rate: 2.1216154368926846e-05
    logging_step: 5
    nums_folds: 5
    loss_name: CrossEntropy # CrossEntropy, focal, label_smoothing, f1
    optimizer_name: AdamW
    lr_sch_use: False
    lr_decay_step: 20
    scheduler_name: StepLR # StepLR, ReduceLROnPlateau, CosineAnnealingLR, constant_warmup
    lr_weight_decay: True
    
wandb:
    wandb_username: dk100
    wandb_project: Data_Experiments
    wandb_entity: re_et