path:
    train_path: ../../dataset/train/aug_kjk.csv       # 엔터티 추가
    test_path: ../../dataset/test/test_data.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등

model:
    model_name: klue/roberta-base
    saved_name: roberta-base_add_entities

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 3
    learning_rate: 1e-5
    logging_step: 5
    nums_folds: 5
    loss_name: CrossEntropy # CrossEntropy, focal, label_smoothing, f1
    optimizer_name: AdamW
    lr_sch_use: False
    lr_decay_step: 20
    scheduler_name: constant_warmup # StepLR, ReduceLROnPlateau, CosineAnnealingLR, constant_warmup
    lr_weight_decay: True
    
wandb:
    wandb_username: dk100
    wandb_project: lv2_personal_test
    wandb_entity: dk100
